FROM	armv7/armhf-debian:jessie
RUN 	apt-get update -y
RUN 	apt-get install -y \
	fuse \
	curl \
	tar \
	bzip2 \
	iputils-ping \
	net-tools
RUN     mkdir -p /opt/infinit \
	&&	cd /opt/infinit \
	&&	curl -q --output infinit.tgz https://storage.googleapis.com/sh_infinit_releases/raspberry/infinit-arm-0.7.3.tar.gz \
	&&	tar xzf infinit.tgz --strip-components=1 -C . \
	&&	rm infinit.tgz
COPY 	pod-setup.sh /root/
RUN 	chmod +x /root/pod-setup.sh
RUN 	mkdir -p /root/logs
RUN 	chmod +w /root/logs
ENV		PATH="/opt/infinit/bin:${PATH}"
RUN 	curl -s https://install.zerotier.com/ | /bin/bash
EXPOSE	9993/udp 6379/udp